# Generated by Django 5.1.5 on 2025-02-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0005_dailyentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='hours_worked',
        ),
    ]
