# Generated by Django 5.1.5 on 2025-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0006_remove_timesheet_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
    ]
