# Generated by Django 5.1.5 on 2025-03-28 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0015_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='project',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='timesheet_app.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
