# Generated by Django 5.1.5 on 2025-03-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0016_remove_dailyentry_project_dailyentry_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='logged_hours',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
    ]
