# Generated by Django 5.1.5 on 2025-03-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0017_alter_task_estimated_hours_alter_task_logged_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_hours',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='outstanding_hours',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
