# Generated by Django 5.1.5 on 2025-03-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0018_alter_project_budget_alter_project_completed_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='overtime_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='regular_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='outstanding_hours',
            field=models.FloatField(verbose_name=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='logged_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='overtime_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
