# Generated by Django 5.1.5 on 2025-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0021_project_is_billable_project_is_internal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_assignment',
            field=models.BooleanField(default=True, help_text='If True, this task must be explicitly assigned'),
        ),
    ]
