# Generated by Django 5.1.5 on 2025-04-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0022_task_requires_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='outstanding_hours',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
