# Generated by Django 5.1.5 on 2025-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0023_alter_project_outstanding_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.FloatField(default=50.0, help_text='Rate per hour for cost estimation'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Optional deadline for task', null=True),
        ),
    ]
