# Generated by Django 5.1.5 on 2025-04-06 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0024_project_hourly_rate_task_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_logged_hours', models.FloatField(default=0.0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('budget_utilized', models.FloatField(default=0.0)),
                ('budget_remaining', models.FloatField(default=0.0)),
                ('over_budget', models.BooleanField(default=False)),
                ('average_task_duration', models.FloatField(default=0.0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_remaining', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='timesheet_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_hours', models.FloatField(default=0.0)),
                ('actual_hours', models.FloatField(default=0.0)),
                ('efficiency_ratio', models.FloatField(default=0.0)),
                ('overdue', models.BooleanField(default=False)),
                ('on_time', models.BooleanField(default=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency', to='timesheet_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('total_hours', models.FloatField(default=0.0)),
                ('productive_hours', models.FloatField(default=0.0)),
                ('admin_hours', models.FloatField(default=0.0)),
                ('utilization_rate', models.FloatField(default=0.0)),
                ('overutilized', models.BooleanField(default=False)),
                ('underutilized', models.BooleanField(default=False)),
                ('balanced', models.BooleanField(default=True)),
                ('context_switch_count', models.IntegerField(default=0)),
                ('average_task_per_day', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
