# Generated by Django 5.1.5 on 2025-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0029_timesheettemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectperformance',
            name='project_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
