# Generated by Django 5.1.5 on 2025-02-18 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0004_remove_timesheet_project_timesheet_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.project')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='timesheet_app.timesheet')),
            ],
        ),
    ]
