# Generated by Django 5.1.5 on 2025-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0011_timesheet_approval_status_timesheet_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
