# Generated by Django 5.1.5 on 2025-03-31 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0019_alter_dailyentry_overtime_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='timesheet_app.timesheet')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(help_text='Hours spent on the task (e.g., 2.5 for 2h30m)')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_entries', to='timesheet_app.dailylog')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet_app.task')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
    ]
