# Generated by Django 5.1.5 on 2025-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0020_dailylog_taskentry_delete_dailyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, help_text='Optional, this is to help categorize the task', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
    ]
