# Generated by Django 5.1.5 on 2025-04-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet_app', '0025_projectperformance_taskefficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeperformance',
            name='high_utilization_weeks',
            field=models.IntegerField(default=0, help_text='Consecutive weeks above 45 productive hours'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='multi_project_load',
            field=models.IntegerField(default=0, help_text='How many active projects is this user working on?'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='project_time_allocation',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of time per project (project_id: hours)'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='utilization_trend',
            field=models.FloatField(default=0.0, help_text="Change from previous week's utilization (%)"),
        ),
        migrations.AddField(
            model_name='projectperformance',
            name='budget_deviation',
            field=models.FloatField(default=0.0, help_text='Difference between projected and actual budget usage'),
        ),
        migrations.AddField(
            model_name='projectperformance',
            name='forecasted_budget_burn',
            field=models.FloatField(default=0.0, help_text='Predicted budget usage based on current burn rate'),
        ),
        migrations.AddField(
            model_name='projectperformance',
            name='high_utilization_streak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectperformance',
            name='multi_project_load',
            field=models.IntegerField(default=0, help_text='Number of users assigned to other projects'),
        ),
        migrations.AddField(
            model_name='projectperformance',
            name='stalled_tasks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectperformance',
            name='tasks_per_week',
            field=models.FloatField(default=0.0, help_text='Average tasks completed per week'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_on',
            field=models.DateField(blank=True, help_text='When the task was completed', null=True),
        ),
        migrations.AddField(
            model_name='taskefficiency',
            name='completion_time',
            field=models.FloatField(default=0.0, help_text='How long this task took to complete (in days)'),
        ),
    ]
